START = {
    "x": 0,
    "y": 0,
    "text": "начало",
    "width": 120,
    "height": 40,
    "type": "Начало / конец",
    "isMenuBlock": False,
    "fontSize": 14,
    "textHeight": 14,
    "isBold": False,
    "isItalic": False,
    "textAlign": "center",
    "labelsPosition": 1,
}
BLOCK = {
    "x": 0,
    "y": 50,
    "text": "a = 10\nb = 20",
    "width": 100,
    "height": 40,
    "type": "Блок",
    "isMenuBlock": False,
    "fontSize": 14,
    "textHeight": 14,
    "isBold": False,
    "isItalic": False,
    "textAlign": "center",
    "labelsPosition": 1,
}

CONDITION = {
    "x": 0,
    "y": 100,
    "text": "b > a",
    "width": 100,
    "height": 40,
    "type": "Условие",
    "isMenuBlock": False,
    "fontSize": 14,
    "textHeight": 14,
    "isBold": False,
    "isItalic": False,
    "textAlign": "center",
    "labelsPosition": 1,
}

INPUT_OUTPUT = {
    "x": 0,
    "y": 50,
    "text": 'вывод "b больше a"',
    "width": 140,
    "height": 40,
    "type": "Ввод / вывод",
    "isMenuBlock": False,
    "fontSize": 14,
    "textHeight": 14,
    "isBold": False,
    "isItalic": False,
    "textAlign": "center",
    "labelsPosition": 1,
}
END = {
    "x": 0,
    "y": 200,
    "text": "конец",
    "width": 100,
    "height": 30,
    "type": "Начало / конец",
    "isMenuBlock": False,
    "fontSize": 14,
    "textHeight": 14,
    "isBold": False,
    "isItalic": False,
    "textAlign": "center",
    "labelsPosition": 1,
}
